name: xp_track
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.2.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_hooks: ^0.20.5
  flutter_localizations:
    sdk: flutter
  fluttertoast: ^8.2.8
  freezed_annotation: ^2.4.4
  gap: ^3.0.1
  go_router: ^14.6.0
  hooks_riverpod: ^2.6.1
  infinite_scroll_pagination: ^4.1.0
  intl: ^0.19.0
  json_annotation: ^4.9.0
  package_info_plus: ^8.1.1
  riverpod_annotation: ^2.6.1
  shared_preferences: ^2.3.3
  sqlite3: ^2.4.7
  url_launcher: ^6.3.1
  path: ^1.9.0
  path_provider: ^2.1.5
  font_awesome_flutter: ^10.8.0
  tekartik_app_flutter_sembast:
    git:
      url: https://github.com/tekartik/app_flutter_utils.dart
      ref: dart3a
      path: app_sembast
  sembast: ^3.7.5+2

dev_dependencies:
  flutter_lints: ^5.0.0
  build_runner: ^2.4.13
  flutter_gen_runner: ^5.8.0
  freezed: ^2.5.7
  go_router_builder: ^2.7.1
  json_serializable: ^6.8.0
  lints: ^5.0.0
  riverpod_generator: ^2.6.2

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/images/

flutter_gen:
  output: lib/src/common/constants/gen/
