name: xp_track
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.2.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_hooks: ^0.20.4
  flutter_localizations:
    sdk: flutter
  fluttertoast: ^8.2.4
  freezed_annotation: ^2.4.1
  gap: ^3.0.1
  go_router: ^13.0.1
  hooks_riverpod: ^2.4.9
  infinite_scroll_pagination: ^4.0.0
  intl: ^0.18.1
  json_annotation: ^4.8.1
  package_info_plus: ^5.0.1
  riverpod_annotation: ^2.3.3
  shared_preferences: ^2.2.2
  drift: ^2.14.1
  sqlite3_flutter_libs: ^0.5.18
  path_provider: ^2.1.1
  path: ^1.8.3
  sqlite3: ^2.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  build_runner: ^2.4.7
  flutter_gen_runner: ^5.3.2
  freezed: ^2.4.6
  go_router_builder: ^2.4.1
  json_serializable: ^6.7.1
  lints: ^3.0.0
  riverpod_generator: ^2.3.9
  drift_dev: ^2.14.1

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/images/

flutter_gen:
  output: lib/src/common/constants/gen/
