import '../domain/currency_info.dart';

final List<String> supportedCurrencyCodes = supportedCurrencyMap.keys.toList();

final Map<String, CurrencyInfo> supportedCurrencyMap = {
  "AFN": CurrencyInfo(code: "AFN", name: "Afghanistan Afghani", symbol: "؋"),
  "ALL": CurrencyInfo(code: "ALL", name: "Albanian Lek", symbol: "Lek"),
  "DZD": CurrencyInfo(code: "DZD", name: "Algerian dinar", symbol: "دج"),
  "ARS": CurrencyInfo(code: "ARS", name: "Argentine Peso", symbol: "\$"),
  "AMD": CurrencyInfo(code: "AMD", name: "Armenian Dram", symbol: "֏"),
  "AUD": CurrencyInfo(code: "AUD", name: "Australian Dollar", symbol: "\$"),
  "AZN": CurrencyInfo(code: "AZN", name: "Azerbaijani Manat", symbol: "₼"),
  "BHD": CurrencyInfo(code: "BHD", name: "Bahraini Dinar", symbol: "BD"),
  "BDT": CurrencyInfo(code: "BDT", name: "Bangladeshi Taka", symbol: "৳"),
  "BBD": CurrencyInfo(code: "BBD", name: "Barbados Dollar", symbol: "\$"),
  "BZD": CurrencyInfo(code: "BZD", name: "Belize Dollar", symbol: "BZ\$"),
  "BMD": CurrencyInfo(code: "BMD", name: "Bermuda Dollar", symbol: "\$"),
  "BTN": CurrencyInfo(code: "BTN", name: "Bhutanese Ngultrum", symbol: "Nu."),
  "BOB": CurrencyInfo(code: "BOB", name: "Bolivia Bolíviano", symbol: "\$b"),
  "BAM": CurrencyInfo(
      code: "BAM",
      name: "Bosnia and Herzegovina convertible mark",
      symbol: "KM"),
  "BWP": CurrencyInfo(code: "BWP", name: "Botswanan Pula", symbol: "P"),
  "BRL": CurrencyInfo(code: "BRL", name: "Brazilian Real", symbol: "R\$"),
  "GBP": CurrencyInfo(code: "GBP", name: "British Pound", symbol: "£"),
  "BND":
      CurrencyInfo(code: "BND", name: "Brunei Darussalam Dollar", symbol: "\$"),
  "BGN": CurrencyInfo(code: "BGN", name: "Bulgarian Lev", symbol: "лв"),
  "BIF": CurrencyInfo(code: "BIF", name: "Burundian Franc", symbol: "FBu"),
  "KHR": CurrencyInfo(code: "KHR", name: "Cambodian riel", symbol: "៛"),
  "CAD": CurrencyInfo(code: "CAD", name: "Canadian Dollar", symbol: "\$"),
  "KYD": CurrencyInfo(code: "KYD", name: "Cayman Islands Dollar", symbol: "\$"),
  "XAF": CurrencyInfo(
      code: "XAF", name: "Central African CFA franc", symbol: "FCFA"),
  "CLP": CurrencyInfo(code: "CLP", name: "Chile Peso", symbol: "\$"),
  "CNY": CurrencyInfo(code: "CNY", name: "China Yuan Renminbi", symbol: "¥"),
  "COP": CurrencyInfo(code: "COP", name: "Colombia Peso", symbol: "\$"),
  "CDF": CurrencyInfo(code: "CDF", name: "Congolese franc", symbol: "FC"),
  "CRC": CurrencyInfo(code: "CRC", name: "Costa Rica Colon", symbol: "₡"),
  "CZK": CurrencyInfo(code: "CZK", name: "Czech Koruna", symbol: "Kč"),
  "DKK": CurrencyInfo(code: "DKK", name: "Denmark Krone", symbol: "kr"),
  "DOP": CurrencyInfo(
      code: "DOP", name: "Dominican Republic Peso", symbol: "RD\$"),
  "EGP": CurrencyInfo(code: "EGP", name: "Egypt Pound", symbol: "£"),
  "AED": CurrencyInfo(code: "AED", name: "Emirati Dirham", symbol: "د.إ"),
  "ETB": CurrencyInfo(code: "ETB", name: "Ethiopian Birr", symbol: "Br"),
  "EUR": CurrencyInfo(code: "EUR", name: "Euro", symbol: "€"),
  "GMD": CurrencyInfo(code: "GMD", name: "Gambian dalasi", symbol: "D"),
  "GEL": CurrencyInfo(code: "GEL", name: "Georgian Lari", symbol: "₾"),
  "GHS": CurrencyInfo(code: "GHS", name: "Ghana Cedi", symbol: "₵"),
  "GTQ": CurrencyInfo(code: "GTQ", name: "Guatemalan quetzal", symbol: "Q"),
  "GYD": CurrencyInfo(code: "GYD", name: "Guyana Dollar", symbol: "\$"),
  "HTG": CurrencyInfo(code: "HTG", name: "Haitian gourde", symbol: "G"),
  "HKD": CurrencyInfo(code: "HKD", name: "Hong Kong Dollar", symbol: "\$"),
  "HUF": CurrencyInfo(code: "HUF", name: "Hungary Forint", symbol: "Ft"),
  "ISK": CurrencyInfo(code: "ISK", name: "Iceland Krona", symbol: "kr"),
  "INR": CurrencyInfo(code: "INR", name: "Indian Rupee", symbol: "₹"),
  "IDR": CurrencyInfo(code: "IDR", name: "Indonesia Rupiah", symbol: "Rp"),
  "IQD": CurrencyInfo(code: "IQD", name: "Iraqi Dinar", symbol: "د.ع"),
  "ILS": CurrencyInfo(code: "ILS", name: "Israel Shekel", symbol: "₪"),
  "JMD": CurrencyInfo(code: "JMD", name: "Jamaica Dollar", symbol: "J\$"),
  "JPY": CurrencyInfo(code: "JPY", name: "Japanese Yen", symbol: "¥"),
  "JOD": CurrencyInfo(code: "JOD", name: "Jordanian dinar", symbol: "د.أ"),
  "KZT": CurrencyInfo(code: "KZT", name: "Kazakhstan Tenge", symbol: "〒"),
  "KES": CurrencyInfo(code: "KES", name: "Kenyan Shilling", symbol: "KSh"),
  "KWD": CurrencyInfo(code: "KWD", name: "Kuwaiti Dinar", symbol: "د.ك"),
  "KGS": CurrencyInfo(code: "KGS", name: "Kyrgyzstani som", symbol: "с"),
  "LAK": CurrencyInfo(code: "LAK", name: "Laos Kip", symbol: "₭"),
  "LRD": CurrencyInfo(code: "LRD", name: "Liberia Dollar", symbol: "\$"),
  "MKD": CurrencyInfo(code: "MKD", name: "Macedonia Denar", symbol: "ден"),
  "MWK": CurrencyInfo(code: "MWK", name: "Malawian Kwacha", symbol: "MK"),
  "MYR": CurrencyInfo(code: "MYR", name: "Malaysia Ringgit", symbol: "RM"),
  "MVR": CurrencyInfo(code: "MVR", name: "Maldivian Rufiyaa", symbol: "/-"),
  "MUR": CurrencyInfo(code: "MUR", name: "Mauritius Rupee", symbol: "₨"),
  "MXN": CurrencyInfo(code: "MXN", name: "Mexico Peso", symbol: "\$"),
  "MDL": CurrencyInfo(code: "MDL", name: "Moldovan Leu", symbol: "L"),
  "MNT": CurrencyInfo(code: "MNT", name: "Mongolia Tughrik", symbol: "₮"),
  "MAD": CurrencyInfo(code: "MAD", name: "Moroccan Dirham", symbol: "MAD"),
  "MZN": CurrencyInfo(code: "MZN", name: "Mozambique Metical", symbol: "MT"),
  "MMK": CurrencyInfo(code: "MMK", name: "Myanmar Kyat", symbol: "Ks"),
  "NAD": CurrencyInfo(code: "NAD", name: "Namibia Dollar", symbol: "\$"),
  "NPR": CurrencyInfo(code: "NPR", name: "Nepal Rupee", symbol: "₨"),
  "NZD": CurrencyInfo(code: "NZD", name: "New Zealand Dollar", symbol: "\$"),
  "NIO": CurrencyInfo(code: "NIO", name: "Nicaragua Cordoba", symbol: "C\$"),
  "NGN": CurrencyInfo(code: "NGN", name: "Nigeria Naira", symbol: "₦"),
  "NOK": CurrencyInfo(code: "NOK", name: "Norway Krone", symbol: "kr"),
  "OMR": CurrencyInfo(code: "OMR", name: "Oman Rial", symbol: "﷼"),
  "PKR": CurrencyInfo(code: "PKR", name: "Pakistan Rupee", symbol: "₨"),
  "PGK": CurrencyInfo(code: "PGK", name: "Papua New Guinean Kina", symbol: "K"),
  "PYG": CurrencyInfo(code: "PYG", name: "Paraguay Guarani", symbol: "₲"),
  "PEN": CurrencyInfo(code: "PEN", name: "Peru Sol", symbol: "S/."),
  "PHP": CurrencyInfo(code: "PHP", name: "Philippines Peso", symbol: "₱"),
  "PLN": CurrencyInfo(code: "PLN", name: "Poland Zloty", symbol: "zł"),
  "QAR": CurrencyInfo(code: "QAR", name: "Qatar Riyal", symbol: "﷼"),
  "RON": CurrencyInfo(code: "RON", name: "Romania Leu", symbol: "L"),
  "RUB": CurrencyInfo(code: "RUB", name: "Russia Ruble", symbol: "₽"),
  "RWF": CurrencyInfo(code: "RWF", name: "Rwandan franc", symbol: "FRw"),
  "SAR": CurrencyInfo(code: "SAR", name: "Saudi Arabia Riyal", symbol: "﷼"),
  "RSD": CurrencyInfo(code: "RSD", name: "Serbia Dinar", symbol: "Дин."),
  "SCR": CurrencyInfo(code: "SCR", name: "Seychellois rupee", symbol: "₨"),
  "SGD": CurrencyInfo(code: "SGD", name: "Singapore Dollar", symbol: "\$"),
  "SOS": CurrencyInfo(code: "SOS", name: "Somalia Shilling", symbol: "S"),
  "ZAR": CurrencyInfo(code: "ZAR", name: "South Africa Rand", symbol: "R"),
  "KRW": CurrencyInfo(code: "KRW", name: "South Korea Won", symbol: "₩"),
  "LKR": CurrencyInfo(code: "LKR", name: "Sri Lanka Rupee", symbol: "₨"),
  "SRD": CurrencyInfo(code: "SRD", name: "Suriname Dollar", symbol: "\$"),
  "SEK": CurrencyInfo(code: "SEK", name: "Sweden Krona", symbol: "kr"),
  "CHF": CurrencyInfo(code: "CHF", name: "Switzerland Franc", symbol: "CHF"),
  "SYP": CurrencyInfo(code: "SYP", name: "Syrian Lira", symbol: "LS"),
  "TWD": CurrencyInfo(code: "TWD", name: "Taiwan New Dollar", symbol: "NT\$"),
  "TZS": CurrencyInfo(code: "TZS", name: "Tanzanian Shilling", symbol: "TSh"),
  "THB": CurrencyInfo(code: "THB", name: "Thailand Baht", symbol: "฿"),
  "TTD": CurrencyInfo(
      code: "TTD", name: "Trinidad and Tobago Dollar", symbol: "TT\$"),
  "TND": CurrencyInfo(code: "TND", name: "Tunisian dinar", symbol: "د.ت"),
  "TRY": CurrencyInfo(code: "TRY", name: "Turkish Lira", symbol: "₺"),
  "XOF": CurrencyInfo(code: "XOF", name: "UEMOA CFA franc", symbol: "FCFA"),
  "UGX": CurrencyInfo(code: "UGX", name: "Ugandan Shilling", symbol: "USh"),
  "UAH": CurrencyInfo(code: "UAH", name: "Ukraine Hryvnia", symbol: "₴"),
  "USD": CurrencyInfo(code: "USD", name: "United States Dollar", symbol: "\$"),
  "UYU": CurrencyInfo(code: "UYU", name: "Uruguay Peso", symbol: "\$U"),
  "VEF": CurrencyInfo(code: "VEF", name: "Venezuela Bolívar", symbol: "Bs"),
  "VND": CurrencyInfo(code: "VND", name: "Vietnamese Dong", symbol: "₫"),
  "YER": CurrencyInfo(code: "YER", name: "Yemen Rial", symbol: "﷼"),
  "ZMW": CurrencyInfo(code: "ZMW", name: "Zambian kwacha", symbol: "ZK"),
};
